/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    logos: Logo;
    articles: Article;
    'live-articles': LiveArticle;
    'job-titles': JobTitle;
    layout: Layout;
    'opinion-page-layout': OpinionPageLayout;
    'features-page-layout': FeaturesPageLayout;
    'staff-page-layout': StaffPageLayout;
    submissions: Submission;
    'event-submissions': EventSubmission;
    'device-tokens': DeviceToken;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'live-articles': LiveArticlesSelect<false> | LiveArticlesSelect<true>;
    'job-titles': JobTitlesSelect<false> | JobTitlesSelect<true>;
    layout: LayoutSelect<false> | LayoutSelect<true>;
    'opinion-page-layout': OpinionPageLayoutSelect<false> | OpinionPageLayoutSelect<true>;
    'features-page-layout': FeaturesPageLayoutSelect<false> | FeaturesPageLayoutSelect<true>;
    'staff-page-layout': StaffPageLayoutSelect<false> | StaffPageLayoutSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'event-submissions': EventSubmissionsSelect<false> | EventSubmissionsSelect<true>;
    'device-tokens': DeviceTokensSelect<false> | DeviceTokensSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    theme: Theme;
    seo: Seo;
  };
  globalsSelect: {
    theme: ThemeSelect<false> | ThemeSelect<true>;
    seo: SeoSelect<false> | SeoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  slug?: string | null;
  roles?: ('admin' | 'eic' | 'editor' | 'writer')[] | null;
  /**
   * Which section this editor manages (only applies to Section Editor role)
   */
  section?: ('news' | 'features' | 'opinion' | 'sports') | null;
  headshot?: (number | null) | Media;
  /**
   * A short one-line description (e.g. "is a senior studying computer science")
   */
  oneLiner?: string | null;
  /**
   * Format: ECSE '28
   */
  major?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  positions?:
    | {
        jobTitle?: (number | null) | JobTitle;
        startDate: string;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  blackTheme?: boolean | null;
  /**
   * Marks this staffer as retired. Retired staff are shown in the RETIRED section on the staff page as "Poly Emeritus" from the end of their last role through the present, and their password is replaced with a long scrambled value without notifying them.
   */
  retired?: boolean | null;
  latestVersion?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * The title of the image, used for alt text across the site.
   */
  title?: string | null;
  alt?: string | null;
  photographer?: (number | null) | User;
  writeInPhotographer?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles".
 */
export interface JobTitle {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  /**
   * Human-readable name shown in the logo picker (e.g. "Default", "Halloween 2026")
   */
  label: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  section: 'news' | 'sports' | 'features' | 'opinion';
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  plainTitle?: string | null;
  kicker?: string | null;
  subdeck?: string | null;
  opinionType?:
    | (
        | 'opinion'
        | 'column'
        | 'staff-editorial'
        | 'editorial-notebook'
        | 'endorsement'
        | 'top-hat'
        | 'candidate-profile'
        | 'letter-to-the-editor'
        | 'polys-recommendations'
        | 'editors-notebook'
        | 'derby'
        | 'other'
        | 'more'
      )
    | null;
  authors?: (number | User)[] | null;
  /**
   * External contributors who are not staff users
   */
  writeInAuthors?:
    | {
        name: string;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  publishedDate?: string | null;
  /**
   * Automatically set to the user who most recently saved this article. Each version in the history tab records the editor who made that change.
   */
  lastModifiedBy?: (number | null) | User;
  featuredImage?: (number | null) | Media;
  imageCaption?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slug?: string | null;
  /**
   * Overrides the article title in search results. Leave blank to use the article title.
   */
  seoTitle?: string | null;
  /**
   * Summary shown in search engine results (150–160 characters recommended).
   */
  searchDescription?: string | null;
  /**
   * Fires a push notification to mobile app users when this article is published.
   */
  breakingNews?: boolean | null;
  /**
   * Render this article in Comic Sans everywhere it appears.
   */
  isFollytechnic?: boolean | null;
  /**
   * Use the full-screen photo feature layout. Only available for single-author articles.
   */
  isPhotofeature?: boolean | null;
  /**
   * Darkness of the bottom image fade (0–100). Default is 90.
   */
  gradientOpacity?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-articles".
 */
export interface LiveArticle {
  id: number;
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Automatically set to the user who most recently saved this live article. Each version captures the editor.
   */
  lastModifiedBy?: (number | null) | User;
  plainTitle: string;
  slug: string;
  /**
   * Short topic label shown on the homepage strip (e.g. "Labor Department", "Election Night").
   */
  section: string;
  hero: number | Media;
  summary?:
    | {
        label: string;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  updates: {
    timestamp: string;
    heading?: string | null;
    author: number | User;
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  publishedDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout".
 */
export interface Layout {
  id: number;
  name: string;
  /**
   * Automatically set to the user who most recently saved the homepage layout. Each version in the history tab records the editor who made that change.
   */
  lastModifiedBy?: (number | null) | User;
  liveArticles?: (number | LiveArticle)[] | null;
  skeleton?: ('custom' | 'aries' | 'taurus' | 'gemini') | null;
  grid?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-section layout configuration (skeleton + pinned articles)
   */
  sectionLayouts?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  mainArticle?: (number | null) | Article;
  top1?: (number | null) | Article;
  top2?: (number | null) | Article;
  top3?: (number | null) | Article;
  top4?: (number | null) | Article;
  op1?: (number | null) | Article;
  op2?: (number | null) | Article;
  op3?: (number | null) | Article;
  op4?: (number | null) | Article;
  special?: (number | null) | Article;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinion-page-layout".
 */
export interface OpinionPageLayout {
  id: number;
  name: string;
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  editorsChoiceLabel?: string | null;
  editorsChoice1?: (number | null) | Article;
  editorsChoice2?: (number | null) | Article;
  editorsChoice3?: (number | null) | Article;
  quotes?:
    | {
        text: string;
        article: number | Article;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-page-layout".
 */
export interface FeaturesPageLayout {
  id: number;
  name: string;
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-page-layout".
 */
export interface StaffPageLayout {
  id: number;
  /**
   * Only the most recently updated document is used on /staff.
   */
  name: string;
  /**
   * Large featured slot in the top-left corner.
   */
  heroLeft?: (number | null) | User;
  /**
   * Large featured slot in the top-right corner.
   */
  heroRight?: (number | null) | User;
  /**
   * Lead slot in the lower-left column.
   */
  columnLeftLead?: (number | null) | User;
  /**
   * Support slot below the lower-left lead.
   */
  columnLeftSupport?: (number | null) | User;
  /**
   * Lead slot in the lower-right column.
   */
  columnRightLead?: (number | null) | User;
  /**
   * Support slot below the lower-right lead.
   */
  columnRightSupport?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  title: string;
  opinionType:
    | 'opinion'
    | 'column'
    | 'staff-editorial'
    | 'editorial-notebook'
    | 'endorsement'
    | 'top-hat'
    | 'candidate-profile'
    | 'letter-to-the-editor'
    | 'polys-recommendations'
    | 'editors-notebook'
    | 'derby'
    | 'other';
  authorName: string;
  /**
   * Email, phone, or other preferred method of contact
   */
  contact: string;
  featuredImage?: (number | null) | Media;
  featuredImageCaption?: string | null;
  content: string;
  status?: ('new' | 'reviewed' | 'published' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-submissions".
 */
export interface EventSubmission {
  id: number;
  eventName: string;
  date: string;
  time: string;
  description: string;
  contactName?: string | null;
  contactInfo?: string | null;
  status?: ('new' | 'reviewed' | 'accepted' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens".
 */
export interface DeviceToken {
  id: number;
  token: string;
  platform: 'android' | 'ios';
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'live-articles';
        value: number | LiveArticle;
      } | null)
    | ({
        relationTo: 'job-titles';
        value: number | JobTitle;
      } | null)
    | ({
        relationTo: 'layout';
        value: number | Layout;
      } | null)
    | ({
        relationTo: 'opinion-page-layout';
        value: number | OpinionPageLayout;
      } | null)
    | ({
        relationTo: 'features-page-layout';
        value: number | FeaturesPageLayout;
      } | null)
    | ({
        relationTo: 'staff-page-layout';
        value: number | StaffPageLayout;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null)
    | ({
        relationTo: 'event-submissions';
        value: number | EventSubmission;
      } | null)
    | ({
        relationTo: 'device-tokens';
        value: number | DeviceToken;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  slug?: T;
  roles?: T;
  section?: T;
  headshot?: T;
  oneLiner?: T;
  major?: T;
  bio?: T;
  positions?:
    | T
    | {
        jobTitle?: T;
        startDate?: T;
        endDate?: T;
        id?: T;
      };
  blackTheme?: T;
  retired?: T;
  latestVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  photographer?: T;
  writeInPhotographer?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  section?: T;
  title?: T;
  plainTitle?: T;
  kicker?: T;
  subdeck?: T;
  opinionType?: T;
  authors?: T;
  writeInAuthors?:
    | T
    | {
        name?: T;
        photo?: T;
        id?: T;
      };
  publishedDate?: T;
  lastModifiedBy?: T;
  featuredImage?: T;
  imageCaption?: T;
  content?: T;
  slug?: T;
  seoTitle?: T;
  searchDescription?: T;
  breakingNews?: T;
  isFollytechnic?: T;
  isPhotofeature?: T;
  gradientOpacity?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-articles_select".
 */
export interface LiveArticlesSelect<T extends boolean = true> {
  title?: T;
  lastModifiedBy?: T;
  plainTitle?: T;
  slug?: T;
  section?: T;
  hero?: T;
  summary?:
    | T
    | {
        label?: T;
        body?: T;
        id?: T;
      };
  updates?:
    | T
    | {
        timestamp?: T;
        heading?: T;
        author?: T;
        body?: T;
        id?: T;
      };
  publishedDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-titles_select".
 */
export interface JobTitlesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "layout_select".
 */
export interface LayoutSelect<T extends boolean = true> {
  name?: T;
  lastModifiedBy?: T;
  liveArticles?: T;
  skeleton?: T;
  grid?: T;
  sectionLayouts?: T;
  mainArticle?: T;
  top1?: T;
  top2?: T;
  top3?: T;
  top4?: T;
  op1?: T;
  op2?: T;
  op3?: T;
  op4?: T;
  special?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opinion-page-layout_select".
 */
export interface OpinionPageLayoutSelect<T extends boolean = true> {
  name?: T;
  layout?: T;
  editorsChoiceLabel?: T;
  editorsChoice1?: T;
  editorsChoice2?: T;
  editorsChoice3?: T;
  quotes?:
    | T
    | {
        text?: T;
        article?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features-page-layout_select".
 */
export interface FeaturesPageLayoutSelect<T extends boolean = true> {
  name?: T;
  layout?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-page-layout_select".
 */
export interface StaffPageLayoutSelect<T extends boolean = true> {
  name?: T;
  heroLeft?: T;
  heroRight?: T;
  columnLeftLead?: T;
  columnLeftSupport?: T;
  columnRightLead?: T;
  columnRightSupport?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  title?: T;
  opinionType?: T;
  authorName?: T;
  contact?: T;
  featuredImage?: T;
  featuredImageCaption?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-submissions_select".
 */
export interface EventSubmissionsSelect<T extends boolean = true> {
  eventName?: T;
  date?: T;
  time?: T;
  description?: T;
  contactName?: T;
  contactInfo?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-tokens_select".
 */
export interface DeviceTokensSelect<T extends boolean = true> {
  token?: T;
  platform?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Automatically set to the user who most recently saved theme settings. Each version captures the editor.
   */
  lastModifiedBy?: (number | null) | User;
  /**
   * Controls the animated wave effect on the header rule line during page transitions.
   */
  headerAnimation?: {
    /**
     * Uncheck to disable the header wave animation entirely — the header rule will render as a static line with no transition effects.
     */
    enabled?: boolean | null;
    /**
     * First gradient stop for the wave effect.
     */
    waveColor1?: string | null;
    /**
     * Second gradient stop for the wave effect.
     */
    waveColor2?: string | null;
    /**
     * Third gradient stop for the wave effect.
     */
    waveColor3?: string | null;
    /**
     * How many wave lines animate across the header (1-8).
     */
    waveCount?: number | null;
    /**
     * Stroke width of the wave and rule lines (0.5-4).
     */
    lineWeight?: number | null;
    /**
     * When enabled, the animation traces around the logo outline before shooting across.
     */
    wrapAround?: boolean | null;
  };
  /**
   * Upload or choose replacement logos for each theme and breakpoint combination. Leave blank to fall back to the static public assets.
   */
  logos?: {
    /**
     * Primary desktop logo shown in light mode.
     */
    desktopLight?: (number | null) | Logo;
    /**
     * Primary desktop logo shown in dark mode.
     */
    desktopDark?: (number | null) | Logo;
    /**
     * Compact logo used in mobile headers and overlays in light mode.
     */
    mobileLight?: (number | null) | Logo;
    /**
     * Compact logo used in mobile headers and overlays in dark mode.
     */
    mobileDark?: (number | null) | Logo;
  };
  /**
   * Live light-mode color tokens used across the frontend. Hex values work best with the picker; rgba values can still be typed manually.
   */
  lightMode?: {
    /**
     * Main page background color.
     */
    background?: string | null;
    /**
     * Primary text color for article and UI copy.
     */
    foreground?: string | null;
    /**
     * Secondary text color for metadata and subdued labels.
     */
    foregroundMuted?: string | null;
    /**
     * Brand accent used for highlights, links, and emphasis.
     */
    accent?: string | null;
    /**
     * Standard border color for cards, chrome, and form edges.
     */
    borderColor?: string | null;
    /**
     * Thin divider color. rgba values are supported.
     */
    ruleColor?: string | null;
    /**
     * Heavy divider color. rgba values are supported.
     */
    ruleStrongColor?: string | null;
    /**
     * Background for the top metadata/date strip.
     */
    headerTopBg?: string | null;
    /**
     * Text color for the top metadata/date strip.
     */
    headerTopText?: string | null;
    /**
     * Main navigation bar background color.
     */
    headerNavBg?: string | null;
    /**
     * Main navigation bar text color.
     */
    headerNavText?: string | null;
    /**
     * Border and rule color used around the header chrome.
     */
    headerBorder?: string | null;
  };
  /**
   * Dark-mode equivalents for the same frontend tokens. These are applied under `html.dark`.
   */
  darkMode?: {
    /**
     * Main page background color in dark mode.
     */
    background?: string | null;
    /**
     * Primary text color in dark mode.
     */
    foreground?: string | null;
    /**
     * Secondary text color in dark mode.
     */
    foregroundMuted?: string | null;
    /**
     * Brand accent used for highlights, links, and emphasis in dark mode.
     */
    accent?: string | null;
    /**
     * Standard border color for dark-mode cards and chrome.
     */
    borderColor?: string | null;
    /**
     * Thin divider color in dark mode. rgba values are supported.
     */
    ruleColor?: string | null;
    /**
     * Heavy divider color in dark mode. rgba values are supported.
     */
    ruleStrongColor?: string | null;
    /**
     * Background for the top metadata/date strip in dark mode.
     */
    headerTopBg?: string | null;
    /**
     * Text color for the top metadata/date strip in dark mode.
     */
    headerTopText?: string | null;
    /**
     * Main navigation bar background in dark mode.
     */
    headerNavBg?: string | null;
    /**
     * Main navigation bar text color in dark mode.
     */
    headerNavText?: string | null;
    /**
     * Border and rule color used around dark-mode header chrome.
     */
    headerBorder?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo".
 */
export interface Seo {
  id: number;
  /**
   * Global brand strings used in page titles, browser metadata, install prompts, and homepage structured data.
   */
  siteIdentity?: {
    /**
     * Primary publication name used for the site title, Open Graph site name, web manifest name, and homepage structured data.
     */
    siteName?: string | null;
    /**
     * Compact app-style name used for the web manifest short name and similar install surfaces.
     */
    siteShortName?: string | null;
    /**
     * Fallback page title used when a route does not provide a more specific title.
     */
    defaultTitle?: string | null;
    /**
     * Suffix appended in the global title template, for example "%s | Title Suffix".
     */
    titleSuffix?: string | null;
    /**
     * Used for the root layout metadata description and homepage metadata description.
     */
    defaultDescription?: string | null;
    /**
     * Shown when the site is saved to an iPhone or iPad home screen.
     */
    appleWebAppTitle?: string | null;
    /**
     * Used in the PWA/web app manifest when the site is installed.
     */
    manifestDescription?: string | null;
    /**
     * Used in homepage Organization JSON-LD output.
     */
    organizationDescription?: string | null;
  };
  /**
   * SEO titles and descriptions for the fixed frontend routes.
   */
  pages?: {
    /**
     * Used for the /archive and /archives page title.
     */
    archiveTitle?: string | null;
    /**
     * Used for the /archive and /archives description and Open Graph description.
     */
    archiveDescription?: string | null;
    /**
     * Used for the /search page title.
     */
    searchTitle?: string | null;
    /**
     * Used for the /search page description.
     */
    searchDescription?: string | null;
    /**
     * Used for the /submit page title.
     */
    submitTitle?: string | null;
    /**
     * Used for the /submit page description.
     */
    submitDescription?: string | null;
    /**
     * Used for the /staff page title.
     */
    staffTitle?: string | null;
    /**
     * Used for the /staff page description and Open Graph description.
     */
    staffDescription?: string | null;
    /**
     * Used for the /features/archive page title.
     */
    featuresArchiveTitle?: string | null;
    /**
     * Used for the /features/archive page description.
     */
    featuresArchiveDescription?: string | null;
    /**
     * Used for the /features/submit-event page title.
     */
    featuresSubmitEventTitle?: string | null;
    /**
     * Used for the /features/submit-event page description.
     */
    featuresSubmitEventDescription?: string | null;
    /**
     * Used for the /opinion/other page title.
     */
    opinionOtherTitle?: string | null;
    /**
     * Used for the /opinion/other page description.
     */
    opinionOtherDescription?: string | null;
    /**
     * Used for the /opinion/editorials page title.
     */
    opinionEditorialsTitle?: string | null;
    /**
     * Used for the /opinion/editorials page description.
     */
    opinionEditorialsDescription?: string | null;
    /**
     * Used for the /opinion/more-in-opinion page title.
     */
    opinionMoreTitle?: string | null;
    /**
     * Used for the /opinion/more-in-opinion page description.
     */
    opinionMoreDescription?: string | null;
    /**
     * Used for the /news/more-in-news page title.
     */
    newsMoreTitle?: string | null;
    /**
     * Used for the /news/more-in-news page description.
     */
    newsMoreDescription?: string | null;
  };
  /**
   * Descriptions used by the top-level section pages like /news, /sports, /features, and /opinion.
   */
  sections?: {
    /**
     * Used for the /news page description and Open Graph description.
     */
    newsDescription?: string | null;
    /**
     * Used for the /sports page description and Open Graph description.
     */
    sportsDescription?: string | null;
    /**
     * Used for the /features page description and Open Graph description.
     */
    featuresDescription?: string | null;
    /**
     * Used for the /opinion page description and Open Graph description.
     */
    opinionDescription?: string | null;
  };
  /**
   * Used when SEO text needs to be generated from page data instead of entered directly.
   */
  templates?: {
    /**
     * Used if a top-level section is missing its dedicated description. Tokens: {section}, {sectionTitle}, {siteName}.
     */
    sectionFallbackDescription?: string | null;
    /**
     * Used when an article has no subdeck. Tokens: {title}, {section}, {sectionTitle}, {siteName}.
     */
    articleFallbackDescription?: string | null;
    /**
     * Used for /staff/[slug] profile descriptions. Tokens: {name}, {siteName}.
     */
    staffProfileDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  lastModifiedBy?: T;
  headerAnimation?:
    | T
    | {
        enabled?: T;
        waveColor1?: T;
        waveColor2?: T;
        waveColor3?: T;
        waveCount?: T;
        lineWeight?: T;
        wrapAround?: T;
      };
  logos?:
    | T
    | {
        desktopLight?: T;
        desktopDark?: T;
        mobileLight?: T;
        mobileDark?: T;
      };
  lightMode?:
    | T
    | {
        background?: T;
        foreground?: T;
        foregroundMuted?: T;
        accent?: T;
        borderColor?: T;
        ruleColor?: T;
        ruleStrongColor?: T;
        headerTopBg?: T;
        headerTopText?: T;
        headerNavBg?: T;
        headerNavText?: T;
        headerBorder?: T;
      };
  darkMode?:
    | T
    | {
        background?: T;
        foreground?: T;
        foregroundMuted?: T;
        accent?: T;
        borderColor?: T;
        ruleColor?: T;
        ruleStrongColor?: T;
        headerTopBg?: T;
        headerTopText?: T;
        headerNavBg?: T;
        headerNavText?: T;
        headerBorder?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo_select".
 */
export interface SeoSelect<T extends boolean = true> {
  siteIdentity?:
    | T
    | {
        siteName?: T;
        siteShortName?: T;
        defaultTitle?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        appleWebAppTitle?: T;
        manifestDescription?: T;
        organizationDescription?: T;
      };
  pages?:
    | T
    | {
        archiveTitle?: T;
        archiveDescription?: T;
        searchTitle?: T;
        searchDescription?: T;
        submitTitle?: T;
        submitDescription?: T;
        staffTitle?: T;
        staffDescription?: T;
        featuresArchiveTitle?: T;
        featuresArchiveDescription?: T;
        featuresSubmitEventTitle?: T;
        featuresSubmitEventDescription?: T;
        opinionOtherTitle?: T;
        opinionOtherDescription?: T;
        opinionEditorialsTitle?: T;
        opinionEditorialsDescription?: T;
        opinionMoreTitle?: T;
        opinionMoreDescription?: T;
        newsMoreTitle?: T;
        newsMoreDescription?: T;
      };
  sections?:
    | T
    | {
        newsDescription?: T;
        sportsDescription?: T;
        featuresDescription?: T;
        opinionDescription?: T;
      };
  templates?:
    | T
    | {
        sectionFallbackDescription?: T;
        articleFallbackDescription?: T;
        staffProfileDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}